GB01:
  EUBI:
    base_number_in_multipack: [3 PACK,SINGLE]
    choco: [DARK,NO]
    flavour: [HONEY,VANILLA,FRUIT_NUTS]
    level_of_sugar: []
    pack_group: []
    product_range: [BELVITA,OREO]
    salty: [YES,NO]
    segment: []
    supersegment: [STANDARD,SEASONAL]
  EUCO:
    base_number_in_multipack: [SINGLE,5 PACK,12 PACK]
    choco: [MILK,DARK]
    flavour: [CITRUS,SEA_SALT,VANILLA]
    level_of_sugar: [STANDARD,LOW SUGAR]
    pack_group: [EVERYDAY BLOCK,PREMIUM SHARE BAGS]
    product_range: [CADBURY DAIRY MILK,GREEN & BLACKS]
    salty: [NO,YES]
    segment: [CHOC BLOCK,CHOC SHARE BAGS]
    supersegment: [STANDARD CHOCOLATE,SHARING]
  EUGC:
    base_number_in_multipack: [7 PACK,SINGLE]
    choco: [NO,DARK]
    flavour: [MINT,PEPPERMINT]
    level_of_sugar: [SUGAR FREE,STANDARD]
    pack_group: [FUNCTIONAL MINT SGLS,SUGAR ADULT SGLS]
    product_range: [HALLS,TRIDENT]
    salty: [NO]
    segment: [MINT SGLS,SUGAR SGLS]
    supersegment: [STANDARD GUM,STANDARD CANDY]
  EUCH:
    base_number_in_multipack: []
    choco: [NO,MILK]
    flavour: [CHEESE,ONION_GARLIC]
    level_of_sugar: []
    pack_group: []
    product_range: [PHILADELPHIA,DAIRYLEA]
    salty: [YES,NO]
    segment: [CREAM CHEESE,SPREADS]
    supersegment: []