GB01:
  EUBI:
    base_number_in_multipack_mult_grouped:
      FIVE: [FIVE--FOUR, FIVE--SIX, FIVE--TWO_TO_THREE]
      SEVEN_OR_MORE: [SEVEN_OR_MORE--SIX]
      SINGLE: [SINGLE--SIX]
    base_number_in_multipack: [SINGLE, 2 PACK, 3 PACK, 4 PACK, 5 PACK, 6 PACK, 7 PACK, 8 PACK, 9 PACK, 10 PACK, 11 PACK, 12 PACK, 13 PACK, 14 PACK, 15 PACK]
    choco: {}
    flavour:
      CHEESE: [PLAIN, PLAIN/WITH BREADSTICKS, PLAIN/RITZ, PLAIN/JUMBO, PLAIN/NACHO, PLAIN/CHEESY CONES, CHEESE & CRACKERS/CRACKER, HERBS/WITH BREADSTICKS, HERB, CHEESE & CRACKERS/CRACKER]
      ONION_GARLIC: [GARLIC & HERBS, CHIVES, CARAMELISED ONION]
      PEPPER: [SWEET CHILLI, JALAPENO]
      FISH: [SALMON]
      CHOCOLATE: [MILK CHOCOLATE]
      BBQ_JUMBO: [BBQ/JUMBO]
      HERB: [HERBS, HERB]
    flavour_mult_grouped:
      FRUIT_NUTS: [CEREAL--FRUIT_NUTS]
      MIXED: [CHOCOLATE--VANILLA]
    flavour_fix: {}
    level_of_sugar: {}
    pack_group: {}
    pack_group_mult_grouped: {}
    product_range:
      7_DAYS: [7 DAYS]
      BARNY: [BARNY]
      BELVITA: [BELVITA]
      CADBURY: [CADBURY]
      CADBURY_CEREAL_BARS: [CADBURY CEREAL BARS]
      LU: [LU]
      MILKA: [MILKA]
      OREO: [OREO]
      RITZ: [RITZ]
    product_range_mult_grouped: {}
    salty_mult_grouped: {}
    segment: {}
    segment_mult_grouped: {}
    supersegment:
      GIVING_SHARING: [GIVING & SHARING]
      SEASONAL: [SEASONAL]
      STANDARD: [STANDARD]
    supersegment_mult_grouped:
      STANDARD: [SEASONAL--STANDARD]
  EUCO:
    base_number_in_multipack_mult_grouped:
      FIVE: [FIVE--FOUR--SIX, FIVE--SIX]
      SINGLE: [FIVE--SINGLE, FOUR--SINGLE]
    base_number_in_multipack: [SINGLE, 2 PACK, 3 PACK, 4 PACK, 5 PACK, 6 PACK, 7 PACK, 8 PACK, 9 PACK, 10 PACK, 11 PACK, 12 PACK, 13 PACK, 14 PACK, 15 PACK]
    choco:
      DARK: [DARK--MILK]
      WHITE: [MILK--WHITE]
    flavour: {}
    flavour_mult_grouped:
      MIXED: [BERRY--CITRUS--FRUIT_NUTS--SALTED_CARAMEL, BERRY--CITRUS--SALTED_CARAMEL, BERRY--SALTED_CARAMEL, BISCUIT--MIXED, CARAMEL--MIXED, CHOCOLATE--MIXED, CITRUS--VANILLA, CHOCOLATE--CITRUS]
      CHOCOLATE: [BISCUIT--CHOCOLATE]
    flavour_fix:
      MIXED: [CARAMEL--CHOCOLATE, CHOCOLATE--FRUIT_NUTS, CHOCOLATE--MIXED, FRUIT_NUTS--VANILLA]
    level_of_sugar:
      LOW_SUGAR: [LOW SUGAR]
      STANDARD: [STANDARD]
    pack_group:
      SEASONAL: [ADVENT CALENDARS, CHRISTMAS NOVELTIES, EASTER NOVELTIES, HALLOWEEN NOVELTIES, SEASONAL SHARE, SELF EAT EASTER NOVS, TREE DECORATIONS]
      AYR_GIFTING: [AYR GIFTING NOVS, EVERYDAY GIFT, GIFT TO SHARE, PREMIUM GIFT]
      CHOC_ADULT_MULTI: [CHOC ADULT MULTI]
      CHOC_ADULT_SGLS: [CHOC ADULT SGLS]
      CHOC_KIDS_MULTI: [CHOC KIDS MULTI]
      CHOC_KIDS_SGLS: [CHOC KIDS SGLS]
      BAG: [CHOCOLATE TRTSZ, EVERYDAY SHARE BAGS, MINI EGGS, PREMIUM SHARE BAGS, SHELL EGGS]
      BLOCK: [EVERYDAY BLOCK, PREMIUM BLOCK]
      MULTI: [SELECTION PACK]
      TUBES: [TUBES]
    pack_group_mult_grouped:
      AYR_GIFTING: [AYR_GIFTING--SEASONAL]
      BAG: [BAG--SEASONAL]
      BLOCK: [BLOCK--SEASONAL]
      MULTI: [MULTI--SEASONAL]
    product_range:
      CADBURY: [CADBURY]
      CADBURY_ALL_OTHERS: [CADBURY BOOST, CADBURY BUTTONS, CADBURY CARAMEL, CADBURY CARAMILK, CADBURY CHOMP, CADBURY CRUNCHIE, CADBURY CURLY WURLY, CADBURY DAIRY MILK FRUITIER & NUTTIER, CADBURY DELIGHTS, CADBURY DINKY DECKERS, CADBURY DOUBLE DECKER, CADBURY FINGERS, CADBURY FLAKE, CADBURY FREDDO, CADBURY FUDGE, CADBURY HEROES, CADBURY MILK TRAY, CADBURY PICNIC, CADBURY PUDS, CADBURY ROSES, CADBURY STARBAR, CADBURY VARIETY]
      CADBURY_BOURNVILLE: [CADBURY BOURNVILLE]
      CADBURY_CREME_EGG: [CADBURY CREME EGG]
      CADBURY_DAIRY_MILK: [CADBURY DAIRY MILK]
      CADBURY_DARKMILK: [CADBURY DARKMILK]
      CADBURY_MINI_EGGS: [CADBURY MINI EGGS]
      CADBURY_TWIRL: [CADBURY TWIRL]
      CADBURY_WISPA: [CADBURY WISPA]
      DAIM: [DAIM]
      FRY_S: [FRY'S, FRY'S CREAM, FRY'S TURKISH DELIGHT]
      GREEN_BLACKS: [GREEN & BLACKS, GREEN & BLACKS VELVET EDITION, GREEN & BLACKS VELVET FRUIT, GREEN AND BLACK'S SMOOTH]
      MAYNARDS_BASSETTS: [MAYNARDS BASSETTS]
      MILKA: [MILKA]
      TOBLERONE: [TOBLERONE]
    product_range_mult_grouped:
      CADBURY_MIXED: [CADBURY_ALL_OTHERS--CADBURY_DAIRY_MILK, CADBURY_BOURNVILLE--CADBURY_DAIRY_MILK, CADBURY_BOURNVILLE--CADBURY_DAIRY_MILK--CADBURY_DARKMILK--TOBLERONE, CADBURY_BOURNVILLE--CADBURY_DAIRY_MILK--TOBLERONE, CADBURY_DAIRY_MILK--CADBURY_DARKMILK--TOBLERONE, CADBURY_DAIRY_MILK--TOBLERONE, CADBURY_DARKMILK--TOBLERONE, CADBURY--CADBURY_ALL_OTHERS, CADBURY--CADBURY_ALL_OTHERS--CADBURY_DAIRY_MILK, CADBURY--CADBURY_ALL_OTHERS--CADBURY_DAIRY_MILK--TOBLERONE, CADBURY--CADBURY_ALL_OTHERS--TOBLERONE, CADBURY--CADBURY_CREME_EGG, CADBURY--CADBURY_DAIRY_MILK, CADBURY--CADBURY_DAIRY_MILK--TOBLERONE]
    salty_mult_grouped:
      NO: [NO--YES]
    segment:
      GIFT: [AYR GIFTING NOVS, EVERYDAY GIFT, GIFT TO SHARE, PREMIUM GIFT, GIFT BLOCK]
      CHOC_BLOCK: [CHOC BLOCK]
      CHOC_MPKS_&_SNK: [CHOC MPKS & SNK]
      CHOC_SGLS: [CHOC SGLS]
      CHOC_SHARE_BAGS: [CHOC SHARE BAGS]
      CHOC_TREATSIZE: [CHOC TREATSIZE]
      SEASONAL_SHARE: [SEASONAL SHARE]
      CHRISTMAS: [TRAD CHRISTMAS]
      EASTER: [TRAD EASTER]
      HALLOWEEN: [TRAD HALLOWEEN]
    segment_mult_grouped:
      CHOC_SHARE_BAGS: [CHOC_SHARE_BAGS--SEASONAL_SHARE]
      GIFT: [CHRISTMAS--GIFT, GIFT--SEASONAL_SHARE]
      SEASONAL_SHARE: [CHRISTMAS--GIFT--SEASONAL_SHARE, CHRISTMAS--SEASONAL_SHARE]
    supersegment:
      GIVING_SHARING: [GIVING, SHARING]
      SEASONAL: [SEASONAL]
      STANDARD_CHOCOLATE: [STANDARD CHOCOLATE]
    supersegment_mult_grouped:
      GIVING_SHARING: [GIVING_SHARING--SEASONAL]
      STANDARD_CHOCOLATE: [GIVING_SHARING--STANDARD_CHOCOLATE]
  EUGC:
    base_number_in_multipack_mult_grouped:
      FOUR: [FOUR--TWO_TO_THREE]
    base_number_in_multipack: [SINGLE, 2 PACK, 3 PACK, 4 PACK, 5 PACK, 6 PACK, 7 PACK, 8 PACK, 9 PACK, 10 PACK, 11 PACK, 12 PACK, 13 PACK, 14 PACK, 15 PACK]
    choco: {}
    flavour: {}
    flavour_mult_grouped: {}
    flavour_fix: {}
    level_of_sugar:
      LOW_SUGAR: [LOW SUGAR]
      STANDARD: [STANDARD]
      SUGAR_FREE: [SUGAR FREE]
    pack_group:
      SEASONAL: [CHRISTMAS NOVELTIES, EASTER NOVELTIES, HALLOWEEN NOVELTIES, SEASONAL SHARE]
      AYR_GIFTING: [GIFT TO SHARE]
      MULTI: [FUNCTIONAL MINT MULTI, MEDICATED MULTI, SUGAR ADULT MULTI]
      SGLS: [FUNCTIONAL MINT SGLS, MEDICATED SGLS, SUGAR ADULT SGLS]
      BAG: [SUGAR FRUIT BAGS, SUGAR MINT BAGS, SUGAR TRAD BAG]
    pack_group_mult_grouped:
      BAG: [BAG--SEASONAL]
    product_range:
      CADBURY_BOURNVILLE: [CADBURY BOURNVILLE]
      CADBURY_ECLAIRS: [CADBURY ECLAIRS]
      HALLS: [HALLS]
      MAYNARDS_BASSETTS: [MAYNARDS BASSETTS]
      SOUR_PATCH_KIDS: [SOUR PATCH KIDS]
      TNCC: [TNCC]
      TREBOR: [TREBOR]
      TRIDENT: [TRIDENT]
    product_range_mult_grouped: {}
    salty_mult_grouped: {}
    segment:
      GIFT_SEASONAL_SHARE: [GIFT TO SHARE, SEASONAL SHARE]
      GUM_SGLS: [GUM SGLS]
      MEDICATED: [MEDICATED]
      MINT_MPKS: [MINT MPKS]
      MINT_SGLS: [MINT SGLS]
      SUGAR_MPKS_&_SNK: [SUGAR MPKS & SNK]
      SUGAR_SGLS: [SUGAR SGLS]
      SUGAR_SHARE_BAGS: [SUGAR SHARE BAGS]
      CHRISTMAS: [TRAD CHRISTMAS]
      EASTER: [TRAD EASTER]
      HALLOWEEN: [TRAD HALLOWEEN]
    segment_mult_grouped:
      SUGAR_SHARE_BAGS: [HALLOWEEN--SUGAR_SHARE_BAGS]
    supersegment:
      SEASONAL: [SEASONAL]
      SHARING: [SHARING]
      STANDARD_CANDY: [STANDARD CANDY]
      STANDARD_GUM: [STANDARD GUM]
    supersegment_mult_grouped:
      STANDARD_CANDY: [SEASONAL--STANDARD_CANDY]
  EUCH:
    base_number_in_multipack_mult_grouped: {}
    base_number_in_multipack: []
    choco: {}
    flavour:
      CHEESE: [PLAIN, PLAIN/WITH BREADSTICKS, PLAIN/RITZ, PLAIN/JUMBO, PLAIN/NACHO, PLAIN/CHEESY CONES, CHEESE & CRACKERS/CRACKER, HERBS/WITH BREADSTICKS, HERB, CHEESE & CRACKERS/CRACKER]
      ONION_GARLIC: [GARLIC & HERBS, CHIVES, CARAMELISED ONION]
      PEPPER: [SWEET CHILLI, JALAPENO]
      FISH: [SALMON]
      CHOCOLATE: [MILK CHOCOLATE]
      BBQ_JUMBO: [BBQ/JUMBO]
      HERB: [HERBS, HERB]
    flavour_mult_grouped: {}
    flavour_fix: {}
    level_of_sugar: {}
    pack_group: {}
    pack_group_mult_grouped: {}
    product_range:
      DAIRYLEA: [DAIRYLEA]
      PHILADELPHIA: [PHILADELPHIA]
    product_range_mult_grouped: {}
    salty_mult_grouped: {}
    segment:
      ADULT_SNACKS: [ADULT SNACKS]
      CREAM_CHEESE: [CREAM CHEESE]
      KIDS_SNACKS: [KIDS SNACKS]
      SLICES: [SLICES]
      SPREADS: [SPREADS]
    segment_mult_grouped: {}
    supersegment: {}
    supersegment_mult_grouped: {}
  EULC:
    base_number_in_multipack_mult_grouped: {}
    base_number_in_multipack: []
    choco: {}
    flavour:
      CHEESE_SALT: [CHICKEN & CHEESE/CRACKER, HAM & CHEESE/CRACKER, MINI PIZZA BASES & STRIP CHEESES/CRACKER]
      CHEESE_CHOCOLATE: [CHEESE & CRACKER & MINI CHOCOLATE COOKIES/CRACKER, CHEESE & CRACKER & GIANT BUTTONS/CRACKER, CHEESE & CRACKERS WITH MINI CADBURY FINGERS/CRACKER]
      CHEESE_OREO: [CHEESE & CRACKER & MINI OREO/MINI OREO]
    flavour_mult_grouped: {}
    flavour_fix: {}
    level_of_sugar: {}
    pack_group: {}
    pack_group_mult_grouped: {}
    product_range:
      DAIRYLEA: [DAIRYLEA]
    product_range_mult_grouped: {}
    salty_mult_grouped: {}
    segment:
      SNACKING_KITS: [SNACKING KITS]
    segment_mult_grouped: {}
    supersegment: {}
    supersegment_mult_grouped: {}