GB01:
  EUBI:
    base_number_in_multipack: [10 PACK,11 PACK,12 PACK,13 PACK,14 PACK,15 PACK,2 PACK,3 PACK,4 PACK,5 PACK,6 PACK,7 PACK,8 PACK,9 PACK,SINGLE]
    choco: [DARK,MILK,NO,WHITE]
    flavour: [BERRY,BUTTER,CARAMEL,CEREAL,CHEESE,CHOCOLATE,CITRUS,FRUIT_NUTS,HERBS,HONEY,MINT,MIXED,OLIVE_CHEESE,ONION_GARLIC,PIZZA,RAISIN,TROPICAL,VANILLA,YOGURT]
    level_of_sugar: []
    pack_group: [] 
    product_range: [7 DAYS,BARNY,BELVITA,CADBURY,CADBURY CEREAL BARS,LU,MILKA,OREO,RITZ]
    salty: [NO,YES]
    segment: []
    supersegment: [GIVING & SHARING,SEASONAL,STANDARD]
  EUCO:
    base_number_in_multipack: [10 PACK,11 PACK,12 PACK,13 PACK,14 PACK,15 PACK,2 PACK,3 PACK,4 PACK,5 PACK,6 PACK,7 PACK,8 PACK,9 PACK,SINGLE]
    choco: [DARK,MILK,WHITE]
    flavour: [BERRY,BISCUIT,BISCUIT_CARAMEL,BUTTERSCOTCH,CARAMEL,CARAMILK,CHOCOLATE,CITRUS,CREME,FRUIT_NUTS,FUDGE,HONEY,JELLY,MINT,MIXED,OREO,SALTED_CARAMEL,SEA_SALT,TROPICAL,VANILLA]
    level_of_sugar: [LOW SUGAR,STANDARD]
    pack_group: [ADVENT CALENDARS,AYR GIFTING NOVS,CHOC ADULT MULTI,CHOC ADULT SGLS,CHOC KIDS MULTI,CHOC KIDS SGLS,CHOCOLATE TRTSZ,CHRISTMAS NOVELTIES,EASTER NOVELTIES,EVERYDAY BLOCK,EVERYDAY GIFT,EVERYDAY SHARE BAGS,GIFT TO SHARE,HALLOWEEN NOVELTIES,MINI EGGS,PREMIUM BLOCK,PREMIUM GIFT,PREMIUM SHARE BAGS,SEASONAL SHARE,SELECTION PACK,SELF EAT EASTER NOVS,SHELL EGGS,TREE DECORATIONS,TUBES]
    product_range: [CADBURY,CADBURY BOOST,CADBURY BOURNVILLE,CADBURY BUTTONS,CADBURY CARAMEL,CADBURY CARAMILK,CADBURY CHOMP,CADBURY CREME EGG,CADBURY CRUNCHIE,CADBURY CURLY WURLY,CADBURY DAIRY MILK,CADBURY DAIRY MILK FRUITIER & NUTTIER,CADBURY DARKMILK,CADBURY DELIGHTS,CADBURY DINKY DECKERS,CADBURY DOUBLE DECKER,CADBURY FINGERS,CADBURY FLAKE,CADBURY FREDDO,CADBURY FUDGE,CADBURY HEROES,CADBURY MILK TRAY,CADBURY MINI EGGS,CADBURY PICNIC,CADBURY PUDS,CADBURY ROSES,CADBURY STARBAR,CADBURY TWIRL,CADBURY VARIETY,CADBURY WISPA,DAIM,FRY'S,FRY'S CREAM,FRY'S TURKISH DELIGHT,GREEN & BLACKS,GREEN & BLACKS VELVET EDITION,GREEN & BLACKS VELVET FRUIT,GREEN AND BLACK'S SMOOTH,MAYNARDS BASSETTS,MILKA,TOBLERONE]
    salty: [NO,YES]
    segment: [AYR GIFTING NOVS,CHOC BLOCK,CHOC MPKS & SNK,CHOC SGLS,CHOC SHARE BAGS,CHOC TREATSIZE,EVERYDAY GIFT,GIFT BLOCK,GIFT TO SHARE,PREMIUM GIFT,SEASONAL SHARE,TRAD CHRISTMAS,TRAD EASTER,TRAD HALLOWEEN]
    supersegment: [GIVING,SEASONAL,SHARING,STANDARD CHOCOLATE]
  EUGC:
    base_number_in_multipack: [10 PACK,11 PACK,12 PACK,13 PACK,14 PACK,15 PACK,2 PACK,3 PACK,4 PACK,5 PACK,6 PACK,7 PACK,8 PACK,9 PACK,SINGLE]
    choco: [DARK,MILK,NO]
    flavour: [BERRY,CARAMEL,CITRUS,CLASSIC,COLA,FRUIT,HONEY_LEMON,LIQUORICE,MENTHOLYPTUS,MINT,MIXED,PEPPERMINT,SPEARMINT,TROPICAL,WINE]
    level_of_sugar: [LOW SUGAR,STANDARD,SUGAR FREE]
    pack_group: [CHRISTMAS NOVELTIES,EASTER NOVELTIES,FUNCTIONAL MINT MULTI,FUNCTIONAL MINT SGLS,GIFT TO SHARE,HALLOWEEN NOVELTIES,MEDICATED MULTI,MEDICATED SGLS,NOT REQUIRED,SEASONAL SHARE,SUGAR ADULT MULTI,SUGAR ADULT SGLS,SUGAR FRUIT BAGS,SUGAR MINT BAGS,SUGAR TRAD BAG]
    product_range: [CADBURY BOURNVILLE,CADBURY ECLAIRS,HALLS,MAYNARDS BASSETTS,SOUR PATCH KIDS,TNCC,TREBOR,TRIDENT]
    salty: [NO]
    segment: [GIFT TO SHARE,GUM SGLS,MEDICATED,MINT MPKS,MINT SGLS,SEASONAL SHARE,SUGAR MPKS & SNK,SUGAR SGLS,SUGAR SHARE BAGS,TRAD CHRISTMAS,TRAD EASTER,TRAD HALLOWEEN]
    supersegment: [SEASONAL,SHARING,STANDARD CANDY,STANDARD GUM]
  EUCH:
    base_number_in_multipack: []
    choco: [MILK,NO]
    flavour: [BBQ_JUMBO,CHEESE,CHOCOLATE,FISH,HERB,ONION_GARLIC,PEPPER]
    level_of_sugar: []
    pack_group: []
    product_range: [DAIRYLEA,PHILADELPHIA]
    salty: [NO,YES]
    segment: [ADULT SNACKS,CREAM CHEESE,KIDS SNACKS,SLICES,SPREADS]
    supersegment: []