name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      # Step 2: Push the `api` folder as a subtree (force push to Hugging Face)
      - name: Push `api` folder to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git subtree split --prefix=api -b temp-branch   # Split `api` folder into a branch
          git push --force https://binaychandra:$HF_TOKEN@huggingface.co/spaces/binaychandra/gamepilot_hfspace temp-branch:main
